---
- hosts: kube-cluster
  gather_facts: yes
  become: yes
  tasks:
    - name: Reset Kubernetes component
      shell: "kubeadm reset -f"
      ignore_errors: True

    - name: Remove docker-ce
      apt:
        name: docker-ce
        state: absent
        force: yes

    - name: Delete flannel.1 interface
      command: ip link delete flannel.1
      when: network == "flannel"
      ignore_errors: True

    - name: Delete cni0 interface
      command: ip link delete cni0
      when: network == "flannel"
      ignore_errors: True
