---
- hosts: kube-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }

- hosts: gpu
  gather_facts: yes
  become: yes
  roles:
    - { role: gpu, tags: gpu }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - {role: csi, tags: csi}

- hosts: gpu
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }
