apiVersion: v1
kind: Secret
metadata:
  name: cpi-global-secret
  namespace: kube-system
stringData:
  {{ vsphere_ip }}.username: "{{ vcenter_user }}"
  {{ vsphere_ip }}.password: "{{ vcenter_pass }}"

